# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aptos-indexer.fullname" . }}
  labels:
    app: {{ include "aptos-indexer.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "aptos-indexer.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "aptos-indexer.name" . }}
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ include "aptos-indexer.fullname" . }}-config
      containers:
        - name: aptos-indexer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config-path
            - /etc/aptos-indexer/indexer.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/aptos-indexer
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aptos-indexer-postgres-password
                  key: POSTGRES_PASSWORD
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key | quote}}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.extraEnvRaw }}
              {{- toYaml .Values.extraEnvRaw | nindent 12 }}
            {{- end }}
          envFrom:
            {{- range .Values.envFromSecrets }}
            - secretRef:
                name: {{ tpl . $ | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.healthCheckPort }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}