# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aptos-indexer.fullname" . }}
  labels:
    app: {{ include "aptos-indexer.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "aptos-indexer.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "aptos-indexer.name" . }}
    spec:
      volumes:
        - name: config-template
          configMap:
            name: {{ include "aptos-indexer.fullname" . }}-config
        - name: config-volume
          emptyDir: {}
      initContainers:
        - name: render-config
          image: "{{ .Values.images.envsubst.repository }}:{{ .Values.images.envsubst.tag }}"
          imagePullPolicy: {{ .Values.images.envsubst.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - envsubst < /config-template/indexer.yaml > /config/indexer.yaml
          env:
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key | quote}}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.extraEnvRaw }}
              {{- toYaml .Values.extraEnvRaw | nindent 12 }}
            {{- end }}
          envFrom:
            {{- range .Values.envFromSecrets }}
            - secretRef:
                name: {{ tpl . $ | quote }}
            {{- end }}
          volumeMounts:
            - name: config-template
              mountPath: /config-template
            - name: config-volume
              mountPath: /config
      containers:
        - name: aptos-indexer
          image: "{{ .Values.images.aptos.repository }}:{{ .Values.images.aptos.tag }}"
          imagePullPolicy: {{ .Values.images.aptos.pullPolicy }}
          args:
            - --config-path
            - /config/indexer.yaml
          volumeMounts:
            - name: config-volume
              mountPath: /config
          env:
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key | quote}}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.extraEnvRaw }}
              {{- toYaml .Values.extraEnvRaw | nindent 12 }}
            {{- end }}
          envFrom:
            {{- range .Values.envFromSecrets }}
            - secretRef:
                name: {{ tpl . $ | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.healthCheckPort }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}