name: Release Helm Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Release helm charts
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_dir: charts
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
