name: Update Helm Chart Index

on:
  push:
    branches:
      - main

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.0  

      - name: Package Helm Chart
        run: |
          helm package ./aptos-indexer-chart
          helm repo index . --url https://ortege-xyz.github.io/helm-charts/

      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
